import React, { useEffect, useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { RippleAPI } from 'ripple-lib';

const api = new RippleAPI({
  server: 'wss://xrplcluster.com' // Public cluster
});
api.connect();

export default function Home() {

  let [isFetching, setIsFetching] = useState(false);
  let [balances, setBalances] = useState([]);
  let [message, setMessage] = useState('');
  let [address, setAddress] = useState('');

  const getBalance = async (address) => {
    setIsFetching(true);
    try {
      const balances = api.getBalances(address)
      return balances;
    } catch(err) {
      setMessage( err.message );
      return err;
    } finally {
      setIsFetching(false);
    }
  }

  const handleSubmit = async (e) => {
    e.preventDefault();
    console.log({e});

    const balances = await getBalance(address);
    console.log({ balances });
    setBalances(balances);
  }

  // useEffect( () => {
  //   const newApi = new RippleAPI({
  //     server: 'wss://xrplcluster.com' // Public cluster
  //   });

  //   setApi( newApi );

  //   api.connect();

  //   console.log(api);
  // }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Check my XRP Balance
        </h1>

        <form className={styles.description} onSubmit={handleSubmit}>
          <label htmlFor="address">
            <span className={styles.formLabel}>Address</span>
            <input id="address" type="text" placeholder="123abc..." value={address} onChange={(e) => setAddress(e.target.value) } className={styles.formInput}/>
          </label>

          <button type="submit" className={styles.formSubmit}>Submit</button>
        </form>

        {message && (
          <p className={styles.description}>
            {message}
          </p>
        )}

        {isFetching && (
          <p>Loading...</p>
        )}

        {balances && (
          <p className={styles.description}>
            {balances.map( balance => {
              return (
                <li key={balance.value}>{balance.currency} Balance: {balance.value}</li>
              )
            })}
          </p>
        )}

      </main>

      <footer className={styles.footer}>
        <a
          href="https://mikelaroy.ca/">
          Made By: Michael LaRoy
        </a>
      </footer>
    </div>
  )
}
